# Important info
dataset_name: 'dataset'
model_name: 'siameseNet18'
backbone: 'none'

output_path: './reports'
random_seed: 42

# StratifiedShuffleSplit
train_size: 0.666
test_size: 0.334
# train_size: 0.334
# test_size: 0.666

# Datasets
final_shape: [280, 320]
dataset_dir: './'
train_dataset:
  augment: False
  grayscale: True
  shuffle: True
test_dataset:
  augment: False
  grayscale: True
  shuffle: False


# Dataloader
train_dataloader:
  batch_size: 64
  drop_last: True
val_dataloader:
  batch_size: 64

# loss
similarity_margin: 2.0
loss: 'contrastive'

# Training
learning_rate: 0.001
epochs: 1000
save_best: True
save_after: 25
