# Dataset
dataset_dir: './'
dataset_name: 'dataset'
final_shape: [320, 280]
grayscale: False
output_path: './reports'

# Model
model_name: 'siameseNet18'
backbone: 'resnet18'

# Training
learning_rate: 0.0001
epochs: 500
save_after: 25
